"""initial schema

Revision ID: cd08d53937db
Revises: 
Create Date: 2026-09-26 00:20:08.971071

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cd08d53937db'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_issue_id', sa.String(length=64), nullable=False),
    sa.Column('repository', sa.String(length=512), nullable=False),
    sa.Column('base_branch', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bug_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_external_issue_id'), ['external_issue_id'], unique=False)

    op.create_table('agent_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_agent_events_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_events'))
    )
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_events_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('candidate_fix', sa.Text(), nullable=False),
    sa.Column('suspected_files', sa.JSON(), nullable=False),
    sa.Column('reproduction_plan', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('patch_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_hypotheses_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses'))
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hypotheses_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('diagnoses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('selected_hypothesis_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('verified_cause', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('rejected_hypotheses', sa.JSON(), nullable=False),
    sa.Column('changed_files', sa.JSON(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_diagnoses_investigation_id_investigations')),
    sa.ForeignKeyConstraint(['selected_hypothesis_id'], ['hypotheses.id'], name=op.f('fk_diagnoses_selected_hypothesis_id_hypotheses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses')),
    sa.UniqueConstraint('investigation_id', name=op.f('uq_diagnoses_investigation_id'))
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('working_directory', sa.String(length=1024), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], name=op.f('fk_experiments_hypothesis_id_hypotheses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_hypothesis_id'), ['hypothesis_id'], unique=False)

    op.create_table('patches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('branch', sa.String(length=256), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('files_changed', sa.JSON(), nullable=False),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], name=op.f('fk_patches_hypothesis_id_hypotheses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patches'))
    )
    with op.batch_alter_table('patches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patches_hypothesis_id'), ['hypothesis_id'], unique=False)

    op.create_table('test_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('test_path', sa.String(length=1024), nullable=False),
    sa.Column('pre_fix_result', sa.String(length=16), nullable=True),
    sa.Column('post_fix_result', sa.String(length=16), nullable=True),
    sa.Column('existing_suite_result', sa.String(length=16), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('failures_before', sa.Integer(), nullable=False),
    sa.Column('failures_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], name=op.f('fk_test_evidence_hypothesis_id_hypotheses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_evidence'))
    )
    with op.batch_alter_table('test_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_evidence_hypothesis_id'), ['hypothesis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_evidence_hypothesis_id'))

    op.drop_table('test_evidence')
    with op.batch_alter_table('patches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patches_hypothesis_id'))

    op.drop_table('patches')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_hypothesis_id'))

    op.drop_table('experiments')
    op.drop_table('diagnoses')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_investigation_id'))

    op.drop_table('hypotheses')
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_agent_events_investigation_id'))

    op.drop_table('agent_events')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_external_issue_id'))

    op.drop_table('investigations')
    # ### end Alembic commands ###
